"use server";
import { Product } from "@/app/admin/dashboard/inventory/page";
import { Tables, TablesInsert } from "@/types_db";
import {
  createProduct,
  updateJobRecord,
  upsertJobRecord,
} from "@/utils/supabase/admin";
import React from "react";

type Job = TablesInsert<"jobs">;

const testProducts: any[] = [
  {
    active: true,
    description: "Over the Range Microwave",
    image: null,
    name: "GE JVM136C",
    price: 49900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 35500,
    model_number: "JVM136C",
    serial_number: "10225688",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Over the Range Microwave",
    image: null,
    name: "GE JVM136B",
    price: 42900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 32500,
    model_number: "JVM136B",
    serial_number: "10255688",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Over the Range Microwave",
    image: null,
    name: "GE JVM136B",
    price: 42900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 32500,
    model_number: "JVM136B",
    serial_number: "10255687",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "GE GSD2600",
    price: 37500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 29900,
    model_number: "GSD2600",
    serial_number: "10899455",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "GE GSD2600",
    price: 37500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 29900,
    model_number: "GSD2600",
    serial_number: "10899456",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "GE GSD2600",
    price: 37500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 29900,
    model_number: "GSD2600",
    serial_number: "10899457",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "GE GSD2600",
    price: 37500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 29900,
    model_number: "GSD2600",
    serial_number: "10899458",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "GE GSD2600",
    price: 37500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 29900,
    model_number: "GSD2600",
    serial_number: "10899459",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "Bosch SHY99A0x",
    price: 89900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 59900,
    model_number: "SHY99A0x",
    serial_number: "58344566",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "Bosch SHY99A0x",
    price: 89900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 59900,
    model_number: "SHY99A0x",
    serial_number: "58344544",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "Bosch SHY99A0x",
    price: 89900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 59900,
    model_number: "SHY99A0x",
    serial_number: "58344533",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "Bosch SHU33A0x",
    price: 73900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 49900,
    model_number: "SHU33A0x",
    serial_number: "56799922",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "Bosch SHU33A0x",
    price: 73900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 49900,
    model_number: "SHU33A0x",
    serial_number: "56799924",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Dishwasher",
    image: null,
    name: "Bosch SHU33A0x",
    price: 73900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 49900,
    model_number: "SHU33A0x",
    serial_number: "56799926",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Laundry Washer",
    image: null,
    name: "Bosch WFL 2060",
    price: 79900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 57900,
    model_number: "WFL 2060",
    serial_number: "98752454",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Laundry Washer",
    image: null,
    name: "Bosch WFL 2060",
    price: 79900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 57900,
    model_number: "WFL 2060",
    serial_number: "98752459",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Laundry Washer",
    image: null,
    name: "Bosch WFL 2060",
    price: 79900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 57900,
    model_number: "WFL 2060",
    serial_number: "98752469",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Laundry Dryer",
    image: null,
    name: "Bosch WTA 3510",
    price: 57900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 39900,
    model_number: "WTA 3510",
    serial_number: "97522146",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Laundry Dryer",
    image: null,
    name: "Bosch WTA 3510",
    price: 57900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 39900,
    model_number: "WTA 3510",
    serial_number: "97522149",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Laundry Dryer",
    image: null,
    name: "Bosch WTA 3510",
    price: 57900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 39900,
    model_number: "WTA 3510",
    serial_number: "97522167",
    brand: "Bosch",
    metadata: {},
  },
  {
    active: true,
    description: "Built-in Refrigerator – 48”",
    image: null,
    name: "Sub Zero SZ632",
    price: 385000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 279900,
    model_number: "SZ632",
    serial_number: "14825844",
    brand: "Sub Zero",
    metadata: {},
  },
  {
    active: true,
    description: "Built-in Refrigerator – 48”",
    image: null,
    name: "Sub Zero SZ632",
    price: 385000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 279900,
    model_number: "SZ632",
    serial_number: "14825848",
    brand: "Sub Zero",
    metadata: {},
  },
  {
    active: true,
    description: "Built-in Refrigerator – 42”",
    image: null,
    name: "Sub Zero SZ680",
    price: 345000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 249900,
    model_number: "SZ680",
    serial_number: "14556688",
    brand: "Sub Zero",
    metadata: {},
  },
  {
    active: true,
    description: "Built-in Wine Cooler – under counter",
    image: null,
    name: "Sub Zero SZ424/S",
    price: 59900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 39900,
    model_number: "SZ424/S",
    serial_number: "25544886",
    brand: "Sub Zero",
    metadata: {},
  },
  {
    active: true,
    description: "24” Professional Gas Range SS",
    image: null,
    name: "Viking VGIC-24",
    price: 399500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 329500,
    model_number: "VGIC-24",
    serial_number: "95778966",
    brand: "Viking",
    metadata: {},
  },
  {
    active: true,
    description: "24” Professional Gas Range SS",
    image: null,
    name: "Viking VGIC-24",
    price: 399500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 329500,
    model_number: "VGIC-24",
    serial_number: "95778998",
    brand: "Viking",
    metadata: {},
  },
  {
    active: true,
    description: "24” Professional Gas Range SS",
    image: null,
    name: "Viking VGIC-24",
    price: 399500,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 329500,
    model_number: "VGIC-24",
    serial_number: "95778983",
    brand: "Viking",
    metadata: {},
  },
  {
    active: true,
    description: "Built-in Coffee System",
    image: null,
    name: "Miele CVA615",
    price: 279900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 149900,
    model_number: "CVA615",
    serial_number: "10897781",
    brand: "Miele",
    metadata: {},
  },
  {
    active: true,
    description: "Double Wall Oven",
    image: null,
    name: "Miele H398BP2",
    price: 375000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 239900,
    model_number: "H398BP2",
    serial_number: "10755389",
    brand: "Miele",
    metadata: {},
  },
  {
    active: true,
    description: "Double Wall Oven",
    image: null,
    name: "Miele H398BP2",
    price: 375000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 239900,
    model_number: "H398BP2",
    serial_number: "10755880",
    brand: "Miele",
    metadata: {},
  },
  {
    active: true,
    description: "Double Wall Oven",
    image: null,
    name: "Miele H398BP2",
    price: 375000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 239900,
    model_number: "H398BP2",
    serial_number: "10757078",
    brand: "Miele",
    metadata: {},
  },
  {
    active: true,
    description: "48” Prostyle Downdraft Cooktop",
    image: null,
    name: "Jenn-Air JGD8348B",
    price: 205900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 149900,
    model_number: "JGD8348B",
    serial_number: "34981101",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "48” Prostyle Downdraft Cooktop",
    image: null,
    name: "Jenn-Air JGD8348B",
    price: 205900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 149900,
    model_number: "JGD8348B",
    serial_number: "34981115",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "48” Prostyle Downdraft Cooktop",
    image: null,
    name: "Jenn-Air JGD8348B",
    price: 205900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 149900,
    model_number: "JGD8348B",
    serial_number: "34981137",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "Double Electric Cooktop",
    image: null,
    name: "Jenn-Air CVEX4270",
    price: 95900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "CVEX4270",
    serial_number: "34987109",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "Double Electric Cooktop",
    image: null,
    name: "Jenn-Air CVEX4270",
    price: 95900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "CVEX4270",
    serial_number: "34987131",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "Double Electric Cooktop",
    image: null,
    name: "Jenn-Air CVEX4270",
    price: 95900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "CVEX4270",
    serial_number: "34987166",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "Double Electric Cooktop",
    image: null,
    name: "Jenn-Air CVEX4270",
    price: 95900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "CVEX4270",
    serial_number: "34987189",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "45” Downdraft Cooktop",
    image: null,
    name: "Jenn-Air JGD8345A",
    price: 148900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 89900,
    model_number: "JGD8345A",
    serial_number: "34986911",
    brand: "Jenn-Air",
    metadata: {},
  },
  {
    active: true,
    description: "Black Free Stand Convection Range",
    image: null,
    name: "Thermador RDFS30QB",
    price: 247900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 179900,
    model_number: "RDFS30QB",
    serial_number: "28946653",
    brand: "Thermador",
    metadata: {},
  },
  {
    active: true,
    description: "Black Free Stand Convection Range",
    image: null,
    name: "Thermador RDFS30QB",
    price: 247900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 179900,
    model_number: "RDFS30QB",
    serial_number: "28946659",
    brand: "Thermador",
    metadata: {},
  },
  {
    active: true,
    description: "Stainless 30” Free Convection Range",
    image: null,
    name: "Thermador RDFS30QB",
    price: 235900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 171900,
    model_number: "RDFS30QB",
    serial_number: "28946667",
    brand: "Thermador",
    metadata: {},
  },
  {
    active: true,
    description: "Stainless 30” Free Convection Range",
    image: null,
    name: "Thermador RDFS30QB",
    price: 235900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 171900,
    model_number: "RDFS30QB",
    serial_number: "28946678",
    brand: "Thermador",
    metadata: {},
  },
  {
    active: true,
    description: "SS Side-by-Side Refrigerator",
    image: null,
    name: "Amana ARSE665B",
    price: 195900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 124900,
    model_number: "ARSE665B",
    serial_number: "5897125",
    brand: "Amana",
    metadata: {},
  },
  {
    active: true,
    description: "SS Side-by-Side Refrigerator",
    image: null,
    name: "Amana ARSE665B",
    price: 195900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 124900,
    model_number: "ARSE665B",
    serial_number: "5897134",
    brand: "Amana",
    metadata: {},
  },
  {
    active: true,
    description: "BL Side-by-Side Refrigerator",
    image: null,
    name: "Amana ARSE665B",
    price: 166900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 104900,
    model_number: "ARSE665B",
    serial_number: "5897167",
    brand: "Amana",
    metadata: {},
  },
  {
    active: true,
    description: "SS Side-by-Side Refrigerator",
    image: null,
    name: "Amana ACD2238H",
    price: 221900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 149500,
    model_number: "ACD2238H",
    serial_number: "5789661",
    brand: "Amana",
    metadata: {},
  },
  {
    active: true,
    description: "SS Side-by-Side Refrigerator",
    image: null,
    name: "Amana ACD2238H",
    price: 221900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 149500,
    model_number: "ACD2238H",
    serial_number: "5789690",
    brand: "Amana",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer",
    image: null,
    name: "Insinkerator 777ss",
    price: 22900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 12900,
    model_number: "777ss",
    serial_number: "55124789",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer",
    image: null,
    name: "Insinkerator 777ss",
    price: 22900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 12900,
    model_number: "777ss",
    serial_number: "55124791",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer",
    image: null,
    name: "Insinkerator 777ss",
    price: 22900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 12900,
    model_number: "777ss",
    serial_number: "55124799",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer",
    image: null,
    name: "Insinkerator Badger5",
    price: 10000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 4900,
    model_number: "Badger5",
    serial_number: "55247891",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer",
    image: null,
    name: "Insinkerator Badger5",
    price: 10000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 4900,
    model_number: "Badger5",
    serial_number: "55247912",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer for Septic Systems",
    image: null,
    name: "Insinkerator Septic120",
    price: 20000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 9900,
    model_number: "Septic120",
    serial_number: "55347925",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "In-Sink Disposer for Septic Systems",
    image: null,
    name: "Insinkerator Septic120",
    price: 20000,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 9900,
    model_number: "Septic120",
    serial_number: "55347937",
    brand: "Insinkerator",
    metadata: {},
  },
  {
    active: true,
    description: "Wine Captain 75 Bottle – SS",
    image: null,
    name: "U-Line 75wc",
    price: 99900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "75wc",
    serial_number: "67555211",
    brand: "U-Line",
    metadata: {},
  },
  {
    active: true,
    description: "Wine Captain 75 Bottle – SS",
    image: null,
    name: "U-Line 75wc",
    price: 99900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "75wc",
    serial_number: "67555225",
    brand: "U-Line",
    metadata: {},
  },
  {
    active: true,
    description: "Wine Captain 75 Bottle – SS",
    image: null,
    name: "U-Line 75wc",
    price: 99900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "75wc",
    serial_number: "67555238",
    brand: "U-Line",
    metadata: {},
  },
  {
    active: true,
    description: "Wine Captain 75 Bottle – SS",
    image: null,
    name: "U-Line 75wc",
    price: 99900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 69900,
    model_number: "75wc",
    serial_number: "67555242",
    brand: "U-Line",
    metadata: {},
  },
  {
    active: true,
    description: "Icemaker – Black",
    image: null,
    name: "U-Line BI98",
    price: 79800,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 49900,
    model_number: "BI98",
    serial_number: "67455891",
    brand: "U-Line",
    metadata: {},
  },
  {
    active: true,
    description: "Microwave – SS",
    image: null,
    name: "GE JVM136B",
    price: 23900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 17900,
    model_number: "JE2160SF",
    serial_number: "15784991",
    brand: "GE",
    metadata: {},
  },
  {
    active: true,
    description: "Range – 36” Pro Dual-Fuel",
    image: null,
    name: "Dacor DOP36M94",
    price: 694900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 439500,
    model_number: "DOP36M94",
    serial_number: "87599365",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "Heritage 30” Stainless Range",
    image: null,
    name: "Dacor HGER30SNG",
    price: 399900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 258900,
    model_number: "HGER30SNG",
    serial_number: "87569821",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "Renaissance 36” Stainless Range",
    image: null,
    name: "Dacor RNRP36GS",
    price: 549900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 389900,
    model_number: "RNRP36GS",
    serial_number: "87589209",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "27” Heritage Collection Wall Oven",
    image: null,
    name: "Dacor HWO127PS",
    price: 401900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 295000,
    model_number: "HWO127PS",
    serial_number: "98562234",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "30” Heritage Collection Pro Style Double Oven",
    image: null,
    name: "Dacor HWO230PS",
    price: 539900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 398500,
    model_number: "HWO230PS",
    serial_number: "98561257",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "Heritage 24 Cu. Ft. Side by Side Built-in Refrig.",
    image: null,
    name: "Dacor DYF42SBIWR",
    price: 799900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 600000,
    model_number: "DYF42SBIWR",
    serial_number: "6345355",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "24” Built-In Dishwasher, Stainless",
    image: null,
    name: "Dacor DDW24M999US",
    price: 89900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 60000,
    model_number: "DDW24M999US",
    serial_number: "5887083",
    brand: "Dacor",
    metadata: {},
  },
  {
    active: true,
    description: "Self-Cleaning Freestanding Double Oven Gas Range, Stainless",
    image: null,
    name: "Dacor HGPR48S/NG",
    price: 959900,
    quantity_available: 0,
    quantity_sold: 0,
    cost: 800000,
    model_number: "HGPR48S/NG",
    serial_number: "6234193",
    brand: "Dacor",
    metadata: {},
  },
];

export const supabaseServer = (job: Job) => {
  return upsertJobRecord(job);
};

export const updateJob = (job: Job) => {
  return updateJobRecord(job);
};

export const supabaseProductCreate = (product: Product) => {
  return createProduct(product);
};

export const loadProductsToSupabase = async () => {
  const products = testProducts; // Assuming testProducts is an array of products

  for (let i = 0; i < products.length; i += 10) {
    const chunk = products.slice(i, i + 10); // Get the next 10 items

    // Create products in Supabase with a delay
    await createProductsChunk(chunk);
    await delay(2000); // Wait for 2 seconds
  }
};

const createProductsChunk = async (products: any[]) => {
  for (const product of products) {
    await createProduct(product); // Assuming createProduct is an asynchronous function to create a product
  }
};

const delay = (ms: number) => {
  return new Promise((resolve) => setTimeout(resolve, ms));
};
